version: "3.8"

services:
  db:
    image: docker.io/postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - podman
    volumes:
      - database_postgres:/var/lib/postresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  api:
    build: .
    container_name: "grpc-microservice"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_TABLE: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_SSL_MODE: "disable"
      DB_TIMEOUT: "30"
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - podman

volumes:
  database_postgres: